#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ghubault <ghubault@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/09/15 11:37:25 by ghubault          #+#    #+#              #
#    Updated: 2014/09/16 23:19:48 by ghubault         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME=		BSQ

HPATH=		ft.h 

SRCS=		*.c

FLAGS=		-Wall -Wextra -Werror

all:
	gcc $(FLAGS) $(SRCS) -o $(NAME)

clean:

fclean: clean
	rm -rf $(NAME)

re: fclean all
